import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import { IsIn, IsOptional, IsString, IsUUID, Length } from 'class-validator';
import { Role } from '../generated/prisma/client.js';

const trim = ({ value }: { value: unknown }): unknown =>
  typeof value === 'string' ? value.trim() : value;

export class CreateWorkspaceDto {
  @ApiPropertyOptional({
    format: 'uuid',
    description:
      'Client-generated UUID v4. Generated by the server if omitted.',
  })
  @IsOptional()
  @IsUUID('4')
  id?: string;

  @ApiProperty({ minLength: 1, maxLength: 80, example: 'Diploma team' })
  @Transform(trim)
  @IsString()
  @Length(1, 80)
  name!: string;
}

export class UpdateWorkspaceDto {
  @ApiProperty({ minLength: 1, maxLength: 80 })
  @Transform(trim)
  @IsString()
  @Length(1, 80)
  name!: string;
}

/** Ownership transfer is out of MVP, so only admin/member are assignable. */
export const ASSIGNABLE_ROLES = [Role.admin, Role.member] as const;
export type AssignableRole = (typeof ASSIGNABLE_ROLES)[number];

export class UpdateMemberRoleDto {
  @ApiProperty({ enum: ASSIGNABLE_ROLES })
  @IsIn(ASSIGNABLE_ROLES)
  role!: AssignableRole;
}

export class WorkspaceDto {
  @ApiProperty({ format: 'uuid' })
  id!: string;

  @ApiProperty()
  name!: string;

  @ApiProperty({ enum: Role, description: "Caller's role" })
  role!: Role;

  @ApiProperty()
  memberCount!: number;

  @ApiProperty()
  createdAt!: Date;

  @ApiProperty()
  updatedAt!: Date;
}

export class MemberUserDto {
  @ApiProperty({ format: 'uuid' })
  id!: string;

  @ApiProperty()
  email!: string;

  @ApiProperty()
  name!: string;

  @ApiPropertyOptional({ type: String, nullable: true })
  avatarUrl!: string | null;
}

export class MemberDto {
  @ApiProperty({ type: MemberUserDto })
  user!: MemberUserDto;

  @ApiProperty({ enum: Role })
  role!: Role;

  @ApiProperty()
  joinedAt!: Date;
}

export class InviteDto {
  @ApiProperty({
    description:
      'Secret token; shown once. Share as flowboard://invite/<token>.',
  })
  token!: string;

  @ApiProperty()
  expiresAt!: Date;
}

export class InvitePreviewDto {
  @ApiProperty({ format: 'uuid' })
  workspaceId!: string;

  @ApiProperty()
  workspaceName!: string;

  @ApiProperty()
  memberCount!: number;

  @ApiProperty()
  expiresAt!: Date;

  @ApiProperty()
  alreadyMember!: boolean;
}
